<project>
	<modelVersion>4.0.0</modelVersion>
	<groupId>RhapsodyOperationEditor</groupId>
	<artifactId>RhapsodyOperationEditor</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>3.5.0</version>
				<executions>
					<execution>
						<id>require-omroot</id>
						<phase>validate</phase>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<requireEnvironmentVariable>
									<variableName>OMROOT</variableName>
								</requireEnvironmentVariable>
								<requireEnvironmentVariable>
									<variableName>USM_ROOT</variableName>
								</requireEnvironmentVariable>
							</rules>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>USM</id>
			<activation>
				<property>
					<name>env.USM_ROOT</name>
				</property>
			</activation>
			<properties>
				<usmroot>${env.USM_ROOT}</usmroot>
			</properties>
			<dependencies>
				<dependency>
					<groupId>vendor.local</groupId>
					<artifactId>cdt</artifactId>
					<version>1.0</version>
					<scope>system</scope>
					<systemPath>
						${usmroot}/Development/Share/Profiles/Bernina/CDT/cdt.jar</systemPath>
				</dependency>
				<dependency>
					<groupId>vendor.local</groupId>
					<artifactId>equinox</artifactId>
					<version>1.0</version>
					<scope>system</scope>
					<systemPath>
						${usmroot}/Development/Share/Profiles/Bernina/CDT/equinox-common-3.2.0.jar</systemPath>
				</dependency>
			</dependencies>
		</profile>

		<profile>
			<id>rhapsody-local</id>
			<activation>
				<property>
					<name>env.OMROOT</name>
				</property>
			</activation>

			<properties>
				<omroot>${env.OMROOT}</omroot>
			</properties>

			<dependencies>
				<dependency>
					<groupId>vendor.local</groupId>
					<artifactId>rhapsody</artifactId>
					<version>1.0</version>
					<scope>system</scope>
					<systemPath>${omroot}/JavaAPI/Rhapsody.jar</systemPath>
				</dependency>

				<dependency>
					<groupId>vendor.local</groupId>
					<artifactId>apps</artifactId>
					<version>1.0</version>
					<scope>system</scope>
					<systemPath>${omroot}/RhapsodyApps/apps.jar</systemPath>
				</dependency>

				<dependency>
					<groupId>vendor.local</groupId>
					<artifactId>rhapsodyapps</artifactId>
					<version>1.0</version>
					<scope>system</scope>
					<systemPath>${omroot}/RhapsodyApps/RhapsodyApps.jar</systemPath>
				</dependency>

				<dependency>
					<groupId>vendor.local</groupId>
					<artifactId>swt</artifactId>
					<version>1.0</version>
					<scope>system</scope>
					<systemPath>${omroot}/RhapsodyApps/libs/swt.jar</systemPath>
				</dependency>

				<dependency>
					<groupId>vendor.local</groupId>
					<artifactId>jdom</artifactId>
					<version>1.0</version>
					<scope>system</scope>
					<systemPath>${omroot}/RhapsodyApps/libs/jdom.jar</systemPath>
				</dependency>


			</dependencies>

		</profile>
	</profiles>

	<dependencies>
		<dependency>
			<groupId>com.fifesoft</groupId>
			<artifactId>rsyntaxtextarea</artifactId>
			<version>3.6.2</version> <!-- oder die neueste Version -->
		</dependency>
		<dependency>
			<groupId>com.fifesoft</groupId>
			<artifactId>autocomplete</artifactId>
			<version>3.3.3</version>
		</dependency>
		<dependency>
			<groupId>io.github.java-diff-utils</groupId>
			<artifactId>java-diff-utils</artifactId>
			<version>4.15</version>
		</dependency>
		<dependency>
			<groupId>com.ibm.icu</groupId>
			<artifactId>icu4j</artifactId>
			<version>77.1</version>
		</dependency>
		<dependency>
			<groupId>com.formdev</groupId>
			<artifactId>flatlaf</artifactId>
			<version>3.4</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-imaging</artifactId>
			<version>1.0.0-alpha6</version>
		</dependency>
	</dependencies>
</project>