package de.schlaich.gunnar.aiTools.mcp.jsonModels;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.telelogic.rhapsody.core.IRPClass;
import com.telelogic.rhapsody.core.IRPClassifier;
import com.telelogic.rhapsody.core.IRPModelElement;
import com.telelogic.rhapsody.core.IRPOperation;
import com.telelogic.rhapsody.core.IRPProject;

public class JsonOperation extends JsonInterfaceItem
{

	/*
	 * java.lang.String getBody() Returns the body of the operation. IRPFlowchart
	 * getFlowchart() Returns the flowchart or activity defined for the operation.
	 * java.lang.String getImplementationSignature() Returns the signature of the
	 * operation as it will appear in the generated code. java.lang.String
	 * getInitializer() For constructors, gets the initializer code that was defined
	 * for the operation. int getIsAbstract() Checks whether the operation was
	 * defined as abstract. int getIsCgDerived() Checks whether the operation is an
	 * operation that is automatically generated by Rhapsody. int getIsConst() For
	 * operations in C++ classes, checks whether the operation was defined as a
	 * constant member function. int getIsCtor() Checks whether the operation is a
	 * constructor. int getIsDtor() Checks whether the operation is a destructor.
	 * int getIsFinal() For operations in Java classes, checks whether the operation
	 * was defined as final. int getIsInline() Checks whether the code for the
	 * operation will be generated inline. int getIsStatic() Checks whether the
	 * operation was defined as static. int getIsTrigger() Checks whether the
	 * operation was defined as a triggered operation. int getIsVirtual() For
	 * operations in C++ or C# classes, checks whether the operation was defined as
	 * virtual. IRPClassifier getReturns() Gets the return type of the operation.
	 * java.lang.String getReturnTypeDeclaration() If an on-the-fly type is used as
	 * the return type of an operation, this method returns the declaration for the
	 * type. java.lang.String getVisibility() Gets the visibility specified
	 */

	@JsonProperty("isAbstract")
	protected boolean isAbstract = false;

	@JsonProperty("isCgDerived")
	protected boolean isCgDerived = false;

	@JsonProperty("isConst")
	protected boolean isConst = false;

	@JsonProperty("isCtor")
	protected boolean isCtor = false;

	@JsonProperty("isDtor")
	protected boolean isDtor = false;

	@JsonProperty("isFinal")
	protected boolean isFinal = false;

	@JsonProperty("isInline")
	protected boolean isInline = false;

	@JsonProperty("isStatic")
	protected boolean isStatic = false;

	@JsonProperty("isTrigger")
	protected boolean isTrigger = false;

	@JsonProperty("isVirtual")
	protected boolean isVirtual = false;

	@JsonProperty("body")
	protected String body = null;

	@JsonProperty(value = "signature", access = JsonProperty.Access.READ_ONLY)
	protected String implementationSignature = null;

	@JsonProperty("initializer")
	protected String initializer = null;

	@JsonProperty("returnTypeDeclaration")
	protected String returnTypeDeclaration = null;

	@JsonProperty("returns")
	protected JsonModelElementBase returns = null;

	@JsonProperty("visibility")
	protected String visibility = null;

	@JsonProperty("flowchart")
	protected JsonModelElementBase flowchart = null;

	public JsonOperation(IRPModelElement aModelElement, int level)
	{
		super(aModelElement, level);

		if (aModelElement == null)
		{
			return;
		}

		if (aModelElement instanceof IRPOperation == false)
		{
			return;
		}

		IRPOperation theOperation = (IRPOperation) aModelElement;

		isAbstract = theOperation.getIsAbstract() == 1;
		isCgDerived = theOperation.getIsCgDerived() == 1;
		isConst = theOperation.getIsConst() == 1;
		isCtor = theOperation.getIsCtor() == 1;
		isDtor = theOperation.getIsDtor() == 1;
		isFinal = theOperation.getIsFinal() == 1;
		isInline = theOperation.getIsInline() == 1;
		isStatic = theOperation.getIsStatic() == 1;
		isTrigger = theOperation.getIsTrigger() == 1;
		isVirtual = theOperation.getIsVirtual() == 1;
		body = theOperation.getBody();
		implementationSignature = theOperation.getImplementationSignature();
		initializer = theOperation.getInitializer();
		returnTypeDeclaration = theOperation.getReturnTypeDeclaration();
		visibility = theOperation.getVisibility();
		if (theOperation.getReturns() != null)
		{
			returns = new JsonModelElementBase(theOperation.getReturns());
		}
		if (theOperation.getFlowchart() != null)
		{
			flowchart = new JsonModelElementBase(theOperation.getFlowchart());
		}

	}

	public IRPModelElement toModelElement(JsonModelElementBase aRootElement, IRPProject aProject, ImportMode importMode)
	{

		if (importMode == ImportMode.reference)
		{
			return super.toModelElement(aRootElement, aProject, importMode);
		}

		if (importMode == ImportMode.remove)
		{
			return super.toModelElement(aRootElement, aProject, importMode);
		}

		IRPOperation operation = null;

		if (importMode == ImportMode.update)
		{
			IRPModelElement existingElement = super.toModelElement(aRootElement, aProject, importMode);

			if (existingElement == null)
			{
				return null;
			}

			if (existingElement instanceof IRPOperation == false)
			{
				return null;
			}

			operation = (IRPOperation) existingElement;
		}

		else if (importMode == ImportMode.create)
		{

			if (this.isDtor || this.isCtor)
			{
				if (aRootElement == null)
				{
					return null;
				}

				IRPModelElement rootElement = aProject.findElementByGUID(aRootElement.getGuid());

				if (rootElement == null)
				{
					return null;
				}
				if (rootElement instanceof IRPClass == false)
				{
					return null;
				}

				IRPClass theClass = (IRPClass) rootElement;

				if (this.isCtor)
				{

					String argumentsData = "";

					List<JsonArgument> arguments = getArguments();

					for (JsonArgument jsonArg : arguments)
					{
						argumentsData += jsonArg.name + "," + jsonArg.vType.name + ",";
					}

					operation = theClass.addConstructor(argumentsData);

				}
				else if (this.isDtor)
				{
					operation = theClass.addDestructor();

				}

				if (operation == null)
				{
					return null;
				}
			}
			else
			{
				IRPModelElement modelElement = super.toModelElement(aRootElement, aProject, importMode);

				if (modelElement == null)
				{
					return null;
				}

				if (modelElement instanceof IRPOperation == false)
				{
					return null;
				}

				operation = (IRPOperation) modelElement;
			}
		}

		operation.setDescription(description);
		operation.setIsVirtual(isVirtual ? 1 : 0);
		if (isSet(visibility))
		{
			operation.setVisibility(visibility);
		}
		if (isSet(initializer))
		{
			operation.setInitializer(initializer);
		}

		setStereotypes(operation, aProject, ImportMode.reference);

		operation.setIsAbstract(isAbstract ? 1 : 0);

		operation.setIsConst(isConst ? 1 : 0);

		operation.setIsFinal(isFinal ? 1 : 0);

		// property...
		// theOperation.setIsInline(isInline ? 1 : 0);
		operation.setIsStatic(isStatic ? 1 : 0);

		operation.setIsVirtual(isVirtual ? 1 : 0);

		if (isSet(body))
		{
			operation.setBody(body);
		}

		operation.setReturnTypeDeclaration(returnTypeDeclaration);
		operation.setVisibility(visibility);

		if (returns != null)
		{
			IRPModelElement returnTypeElement = returns.toModelElement(aProject, ImportMode.update);

			operation.setReturns((IRPClassifier) returnTypeElement);
		}

		return operation;
	}

	public JsonOperation()
	{
		// TODO Auto-generated constructor stub
	}

	private List<JsonArgument> getArguments()
	{
		List<JsonArgument> arguments = new ArrayList<>();

		for (JsonModelElementBase jsonNestedElement : this.nestedElements)
		{
			if (jsonNestedElement instanceof JsonArgument)
			{
				arguments.add((JsonArgument) jsonNestedElement);
			}

		}

		return arguments;
	}

}
