/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ContentPermissionRequest;
import io.swagger.client.model.PermissionCheckResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ContentPermissionsApi
 */
@Ignore
public class ContentPermissionsApiTest {

    private final ContentPermissionsApi api = new ContentPermissionsApi();

    /**
     * Check content permissions
     *
     * Check if a user or a group can perform an operation to the specified content. The &#x60;operation&#x60; to check must be provided. The user’s account ID or the ID of the group can be provided in the &#x60;subject&#x60; to check permissions against a specified user or group. The following permission checks are done to make sure that the user or group has the proper access:  - site permissions - space permissions - content restrictions  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#x27;Can use&#x27; global permission) if checking permission for self, otherwise &#x27;Confluence Administrator&#x27; global permission is required.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void checkContentPermissionTest() throws Exception {
        ContentPermissionRequest body = null;
        String id = null;
        PermissionCheckResponse response = api.checkContentPermission(body, id);

        // TODO: test validations
    }
}
