/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.LookAndFeel;
import io.swagger.client.model.LookAndFeelSelection;
import io.swagger.client.model.LookAndFeelSettings;
import io.swagger.client.model.LookAndFeelWithLinks;
import io.swagger.client.model.SystemInfoEntity;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for SettingsApi
 */
@Ignore
public class SettingsApiTest {

    private final SettingsApi api = new SettingsApi();

    /**
     * Get look and feel settings
     *
     * Returns the look and feel settings for the site or a single space. This includes attributes such as the color scheme, padding, and border radius.  The look and feel settings for a space can be inherited from the global look and feel settings or provided by a theme.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: None
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getLookAndFeelSettingsTest() throws Exception {
        String spaceKey = null;
        LookAndFeelSettings response = api.getLookAndFeelSettings(spaceKey);

        // TODO: test validations
    }
    /**
     * Get system info
     *
     * Returns the system information for the Confluence Cloud tenant. This information is used by Atlassian.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#x27;Can use&#x27; global permission).
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSystemInfoTest() throws Exception {
        SystemInfoEntity response = api.getSystemInfo();

        // TODO: test validations
    }
    /**
     * Reset look and feel settings
     *
     * Resets the custom look and feel settings for the site or a single space. This changes the values of the custom settings to be the same as the default settings. It does not change which settings (default or custom) are selected. Note, the default space settings are inherited from the current global settings.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;Admin&#x27; permission for the space.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void resetLookAndFeelSettingsTest() throws Exception {
        String spaceKey = null;
        api.resetLookAndFeelSettings(spaceKey);

        // TODO: test validations
    }
    /**
     * Set look and feel settings
     *
     * Sets the look and feel settings to either the default settings or the custom settings, for the site or a single space. Note, the default space settings are inherited from the current global settings.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;Admin&#x27; permission for the space.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void setLookAndFeelSettingsTest() throws Exception {
        String body = null;
        String spaceKey = null;
        String response = api.setLookAndFeelSettings(body, spaceKey);

        // TODO: test validations
    }
    /**
     * Select look and feel settings
     *
     * Sets the look and feel settings to the default (global) settings, the custom settings, or the current theme&#x27;s settings for a space. The custom and theme settings can only be selected if there is already a theme set for a space. Note, the default space settings are inherited from the current global settings.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;Admin&#x27; permission for the space.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateLookAndFeelTest() throws Exception {
        LookAndFeelSelection body = null;
        LookAndFeelSelection response = api.updateLookAndFeel(body);

        // TODO: test validations
    }
    /**
     * Update look and feel settings
     *
     * Updates the look and feel settings for the site or for a single space. If custom settings exist, they are updated. If no custom settings exist, then a set of custom settings is created.  Note, if a theme is selected for a space, the space look and feel settings are provided by the theme and cannot be overridden.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;Admin&#x27; permission for the space.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateLookAndFeelSettingsTest() throws Exception {
        LookAndFeel body = null;
        String spaceKey = null;
        LookAndFeelWithLinks response = api.updateLookAndFeelSettings(body, spaceKey);

        // TODO: test validations
    }
}
