/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ContentArray;
import io.swagger.client.model.InlineResponse2001;
import io.swagger.client.model.LongTask;
import io.swagger.client.model.Space;
import io.swagger.client.model.SpaceArray;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for SpaceApi
 */
@Ignore
public class SpaceApiTest {

    private final SpaceApi api = new SpaceApi();

    /**
     * Create private space
     *
     * Creates a new space that is only visible to the creator. This method is the same as the [Create space](#api-space-post) method with permissions set to the current user only. Note, currently you cannot set space labels when creating a space.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;Create Space(s)&#x27; global permission.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createPrivateSpaceTest() throws Exception {
        Map<String, Object> body = null;
        Space response = api.createPrivateSpace(body);

        // TODO: test validations
    }
    /**
     * Create space
     *
     * Creates a new space. Note, currently you cannot set space labels when creating a space.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;Create Space(s)&#x27; global permission.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createSpaceTest() throws Exception {
        Map<String, Object> body = null;
        Space response = api.createSpace(body);

        // TODO: test validations
    }
    /**
     * Delete space
     *
     * Deletes a space. Note, the space will be deleted in a long running task. Therefore, the space may not be deleted yet when this method has returned. Clients should poll the status link that is returned in the response until the task completes.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;Admin&#x27; permission for the space.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteSpaceTest() throws Exception {
        String spaceKey = null;
        LongTask response = api.deleteSpace(spaceKey);

        // TODO: test validations
    }
    /**
     * Get content by type for space
     *
     * Deprecated, use [Confluence&#x27;s v2 API](https://developer.atlassian.com/cloud/confluence/rest/v2/intro/).  Returns all content of a given type, in a space. The returned content is ordered by content ID in ascending order.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;View&#x27; permission for the space. Note, the returned list will only contain content that the current user has permission to view.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getContentByTypeForSpaceTest() throws Exception {
        String spaceKey = null;
        String type = null;
        String depth = null;
        List<String> expand = null;
        Integer start = null;
        Integer limit = null;
        ContentArray response = api.getContentByTypeForSpace(spaceKey, type, depth, expand, start, limit);

        // TODO: test validations
    }
    /**
     * Get content for space
     *
     * Deprecated, use [Confluence&#x27;s v2 API](https://developer.atlassian.com/cloud/confluence/rest/v2/intro/).  Returns all content in a space. The returned content is grouped by type (pages then blogposts), then ordered by content ID in ascending order.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;View&#x27; permission for the space. Note, the returned list will only contain content that the current user has permission to view.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getContentForSpaceTest() throws Exception {
        String spaceKey = null;
        String depth = null;
        List<String> expand = null;
        Integer start = null;
        Integer limit = null;
        InlineResponse2001 response = api.getContentForSpace(spaceKey, depth, expand, start, limit);

        // TODO: test validations
    }
    /**
     * Get space
     *
     * Deprecated, use [Confluence&#x27;s v2 API](https://developer.atlassian.com/cloud/confluence/rest/v2/intro/).  Returns a space. This includes information like the name, description, and permissions, but not the content in the space.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;View&#x27; permission for the space.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSpaceTest() throws Exception {
        String spaceKey = null;
        List<String> expand = null;
        Space response = api.getSpace(spaceKey, expand);

        // TODO: test validations
    }
    /**
     * Get spaces
     *
     * Deprecated, use [Confluence&#x27;s v2 API](https://developer.atlassian.com/cloud/confluence/rest/v2/intro/).  Returns all spaces. The returned spaces are ordered alphabetically in ascending order by space key.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#x27;Can use&#x27; global permission). Note, the returned list will only contain spaces that the current user has permission to view.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSpacesTest() throws Exception {
        List<String> spaceKey = null;
        List<Long> spaceId = null;
        String type = null;
        String status = null;
        List<String> label = null;
        Boolean favourite = null;
        String favouriteUserKey = null;
        List<String> expand = null;
        Integer start = null;
        Integer limit = null;
        SpaceArray response = api.getSpaces(spaceKey, spaceId, type, status, label, favourite, favouriteUserKey, expand, start, limit);

        // TODO: test validations
    }
    /**
     * Update space
     *
     * Updates the name, description, or homepage of a space.  -   For security reasons, permissions cannot be updated via the API and must be changed via the user interface instead. -   Currently you cannot set space labels when updating a space.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;Admin&#x27; permission for the space.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateSpaceTest() throws Exception {
        Map<String, Object> body = null;
        String spaceKey = null;
        Space response = api.updateSpace(body, spaceKey);

        // TODO: test validations
    }
}
