/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BulkUserLookupExpandable;
import io.swagger.client.model.GenericLinks;
import io.swagger.client.model.Icon;
import io.swagger.client.model.OperationCheckResult;
import io.swagger.client.model.Space;
import io.swagger.client.model.UserDetails;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * BulkUserLookup
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-29T20:08:21.572793104Z[GMT]")
public class BulkUserLookup {
  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    KNOWN("known"),
    UNKNOWN("unknown"),
    ANONYMOUS("anonymous"),
    USER("user");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return TypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("userKey")
  private String userKey = null;

  @SerializedName("accountId")
  private String accountId = null;

  @SerializedName("accountType")
  private String accountType = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("publicName")
  private String publicName = null;

  @SerializedName("profilePicture")
  private Icon profilePicture = null;

  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("timeZone")
  private String timeZone = null;

  @SerializedName("isExternalCollaborator")
  private Boolean isExternalCollaborator = null;

  @SerializedName("operations")
  private List<OperationCheckResult> operations = null;

  @SerializedName("details")
  private UserDetails details = null;

  @SerializedName("personalSpace")
  private Space personalSpace = null;

  @SerializedName("_expandable")
  private BulkUserLookupExpandable _expandable = null;

  @SerializedName("_links")
  private GenericLinks _links = null;

  public BulkUserLookup type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public BulkUserLookup username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @Schema(description = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public BulkUserLookup userKey(String userKey) {
    this.userKey = userKey;
    return this;
  }

   /**
   * Get userKey
   * @return userKey
  **/
  @Schema(description = "")
  public String getUserKey() {
    return userKey;
  }

  public void setUserKey(String userKey) {
    this.userKey = userKey;
  }

  public BulkUserLookup accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @Schema(required = true, description = "")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public BulkUserLookup accountType(String accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * The account type of the user, may return empty string if unavailable.
   * @return accountType
  **/
  @Schema(required = true, description = "The account type of the user, may return empty string if unavailable.")
  public String getAccountType() {
    return accountType;
  }

  public void setAccountType(String accountType) {
    this.accountType = accountType;
  }

  public BulkUserLookup email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The email address of the user. Depending on the user&#x27;s privacy setting, this may return an empty string.
   * @return email
  **/
  @Schema(required = true, description = "The email address of the user. Depending on the user's privacy setting, this may return an empty string.")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public BulkUserLookup publicName(String publicName) {
    this.publicName = publicName;
    return this;
  }

   /**
   * The public name or nickname of the user. Will always contain a value.
   * @return publicName
  **/
  @Schema(required = true, description = "The public name or nickname of the user. Will always contain a value.")
  public String getPublicName() {
    return publicName;
  }

  public void setPublicName(String publicName) {
    this.publicName = publicName;
  }

  public BulkUserLookup profilePicture(Icon profilePicture) {
    this.profilePicture = profilePicture;
    return this;
  }

   /**
   * Get profilePicture
   * @return profilePicture
  **/
  @Schema(required = true, description = "")
  public Icon getProfilePicture() {
    return profilePicture;
  }

  public void setProfilePicture(Icon profilePicture) {
    this.profilePicture = profilePicture;
  }

  public BulkUserLookup displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The displays name of the user. Depending on the user&#x27;s privacy setting, this may be the same as publicName.
   * @return displayName
  **/
  @Schema(required = true, description = "The displays name of the user. Depending on the user's privacy setting, this may be the same as publicName.")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public BulkUserLookup timeZone(String timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * This displays user time zone. Depending on the user&#x27;s privacy setting, this may return null.
   * @return timeZone
  **/
  @Schema(description = "This displays user time zone. Depending on the user's privacy setting, this may return null.")
  public String getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(String timeZone) {
    this.timeZone = timeZone;
  }

  public BulkUserLookup isExternalCollaborator(Boolean isExternalCollaborator) {
    this.isExternalCollaborator = isExternalCollaborator;
    return this;
  }

   /**
   * Whether the user is an external collaborator user
   * @return isExternalCollaborator
  **/
  @Schema(description = "Whether the user is an external collaborator user")
  public Boolean isIsExternalCollaborator() {
    return isExternalCollaborator;
  }

  public void setIsExternalCollaborator(Boolean isExternalCollaborator) {
    this.isExternalCollaborator = isExternalCollaborator;
  }

  public BulkUserLookup operations(List<OperationCheckResult> operations) {
    this.operations = operations;
    return this;
  }

  public BulkUserLookup addOperationsItem(OperationCheckResult operationsItem) {
    if (this.operations == null) {
      this.operations = new ArrayList<OperationCheckResult>();
    }
    this.operations.add(operationsItem);
    return this;
  }

   /**
   * Get operations
   * @return operations
  **/
  @Schema(description = "")
  public List<OperationCheckResult> getOperations() {
    return operations;
  }

  public void setOperations(List<OperationCheckResult> operations) {
    this.operations = operations;
  }

  public BulkUserLookup details(UserDetails details) {
    this.details = details;
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @Schema(description = "")
  public UserDetails getDetails() {
    return details;
  }

  public void setDetails(UserDetails details) {
    this.details = details;
  }

  public BulkUserLookup personalSpace(Space personalSpace) {
    this.personalSpace = personalSpace;
    return this;
  }

   /**
   * Get personalSpace
   * @return personalSpace
  **/
  @Schema(description = "")
  public Space getPersonalSpace() {
    return personalSpace;
  }

  public void setPersonalSpace(Space personalSpace) {
    this.personalSpace = personalSpace;
  }

  public BulkUserLookup _expandable(BulkUserLookupExpandable _expandable) {
    this._expandable = _expandable;
    return this;
  }

   /**
   * Get _expandable
   * @return _expandable
  **/
  @Schema(required = true, description = "")
  public BulkUserLookupExpandable getExpandable() {
    return _expandable;
  }

  public void setExpandable(BulkUserLookupExpandable _expandable) {
    this._expandable = _expandable;
  }

  public BulkUserLookup _links(GenericLinks _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(required = true, description = "")
  public GenericLinks getLinks() {
    return _links;
  }

  public void setLinks(GenericLinks _links) {
    this._links = _links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkUserLookup bulkUserLookup = (BulkUserLookup) o;
    return Objects.equals(this.type, bulkUserLookup.type) &&
        Objects.equals(this.username, bulkUserLookup.username) &&
        Objects.equals(this.userKey, bulkUserLookup.userKey) &&
        Objects.equals(this.accountId, bulkUserLookup.accountId) &&
        Objects.equals(this.accountType, bulkUserLookup.accountType) &&
        Objects.equals(this.email, bulkUserLookup.email) &&
        Objects.equals(this.publicName, bulkUserLookup.publicName) &&
        Objects.equals(this.profilePicture, bulkUserLookup.profilePicture) &&
        Objects.equals(this.displayName, bulkUserLookup.displayName) &&
        Objects.equals(this.timeZone, bulkUserLookup.timeZone) &&
        Objects.equals(this.isExternalCollaborator, bulkUserLookup.isExternalCollaborator) &&
        Objects.equals(this.operations, bulkUserLookup.operations) &&
        Objects.equals(this.details, bulkUserLookup.details) &&
        Objects.equals(this.personalSpace, bulkUserLookup.personalSpace) &&
        Objects.equals(this._expandable, bulkUserLookup._expandable) &&
        Objects.equals(this._links, bulkUserLookup._links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, username, userKey, accountId, accountType, email, publicName, profilePicture, displayName, timeZone, isExternalCollaborator, operations, details, personalSpace, _expandable, _links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkUserLookup {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    userKey: ").append(toIndentedString(userKey)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    publicName: ").append(toIndentedString(publicName)).append("\n");
    sb.append("    profilePicture: ").append(toIndentedString(profilePicture)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    isExternalCollaborator: ").append(toIndentedString(isExternalCollaborator)).append("\n");
    sb.append("    operations: ").append(toIndentedString(operations)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    personalSpace: ").append(toIndentedString(personalSpace)).append("\n");
    sb.append("    _expandable: ").append(toIndentedString(_expandable)).append("\n");
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
