/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ContentRestrictionUpdateRestrictionsGroup;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * The users/groups that the restrictions will be applied to. At least one of &#x60;user&#x60; or &#x60;group&#x60; must be specified for this object.
 */
@Schema(description = "The users/groups that the restrictions will be applied to. At least one of `user` or `group` must be specified for this object.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-29T20:08:21.572793104Z[GMT]")
public class ContentRestrictionUpdateRestrictions {
  @SerializedName("group")
  private List<ContentRestrictionUpdateRestrictionsGroup> group = null;

  @SerializedName("user")
  private OneOfContentRestrictionUpdateRestrictionsUser user = null;

  public ContentRestrictionUpdateRestrictions group(List<ContentRestrictionUpdateRestrictionsGroup> group) {
    this.group = group;
    return this;
  }

  public ContentRestrictionUpdateRestrictions addGroupItem(ContentRestrictionUpdateRestrictionsGroup groupItem) {
    if (this.group == null) {
      this.group = new ArrayList<ContentRestrictionUpdateRestrictionsGroup>();
    }
    this.group.add(groupItem);
    return this;
  }

   /**
   * The groups that the restrictions will be applied to. This array must have at least one item, otherwise it should be omitted.
   * @return group
  **/
  @Schema(description = "The groups that the restrictions will be applied to. This array must have at least one item, otherwise it should be omitted.")
  public List<ContentRestrictionUpdateRestrictionsGroup> getGroup() {
    return group;
  }

  public void setGroup(List<ContentRestrictionUpdateRestrictionsGroup> group) {
    this.group = group;
  }

  public ContentRestrictionUpdateRestrictions user(OneOfContentRestrictionUpdateRestrictionsUser user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @Schema(description = "")
  public OneOfContentRestrictionUpdateRestrictionsUser getUser() {
    return user;
  }

  public void setUser(OneOfContentRestrictionUpdateRestrictionsUser user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContentRestrictionUpdateRestrictions contentRestrictionUpdateRestrictions = (ContentRestrictionUpdateRestrictions) o;
    return Objects.equals(this.group, contentRestrictionUpdateRestrictions.group) &&
        Objects.equals(this.user, contentRestrictionUpdateRestrictions.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(group, user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContentRestrictionUpdateRestrictions {\n");
    
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
