/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ContentArray;
import io.swagger.client.model.GenericLinks;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
/**
 * ContentChildren
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-29T20:08:21.572793104Z[GMT]")
public class ContentChildren extends HashMap<String, Object> {
  @SerializedName("attachment")
  private ContentArray attachment = null;

  @SerializedName("comment")
  private ContentArray comment = null;

  @SerializedName("page")
  private ContentArray page = null;

  @SerializedName("_expandable")
  private Map _expandable = null;

  @SerializedName("_links")
  private GenericLinks _links = null;

  public ContentChildren attachment(ContentArray attachment) {
    this.attachment = attachment;
    return this;
  }

   /**
   * Get attachment
   * @return attachment
  **/
  @Schema(description = "")
  public ContentArray getAttachment() {
    return attachment;
  }

  public void setAttachment(ContentArray attachment) {
    this.attachment = attachment;
  }

  public ContentChildren comment(ContentArray comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @Schema(description = "")
  public ContentArray getComment() {
    return comment;
  }

  public void setComment(ContentArray comment) {
    this.comment = comment;
  }

  public ContentChildren page(ContentArray page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @Schema(description = "")
  public ContentArray getPage() {
    return page;
  }

  public void setPage(ContentArray page) {
    this.page = page;
  }

  public ContentChildren _expandable(Map _expandable) {
    this._expandable = _expandable;
    return this;
  }

   /**
   * Get _expandable
   * @return _expandable
  **/
  @Schema(description = "")
  public Map getExpandable() {
    return _expandable;
  }

  public void setExpandable(Map _expandable) {
    this._expandable = _expandable;
  }

  public ContentChildren _links(GenericLinks _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(description = "")
  public GenericLinks getLinks() {
    return _links;
  }

  public void setLinks(GenericLinks _links) {
    this._links = _links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContentChildren contentChildren = (ContentChildren) o;
    return Objects.equals(this.attachment, contentChildren.attachment) &&
        Objects.equals(this.comment, contentChildren.comment) &&
        Objects.equals(this.page, contentChildren.page) &&
        Objects.equals(this._expandable, contentChildren._expandable) &&
        Objects.equals(this._links, contentChildren._links) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachment, comment, page, _expandable, _links, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContentChildren {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    attachment: ").append(toIndentedString(attachment)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    _expandable: ").append(toIndentedString(_expandable)).append("\n");
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
