/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BulkUserLookupExpandable;
import io.swagger.client.model.GenericLinks;
import io.swagger.client.model.Icon;
import io.swagger.client.model.OperationCheckResult;
import io.swagger.client.model.Space;
import io.swagger.client.model.UserDetails;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * User
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-29T20:08:21.572793104Z[GMT]")
public class User extends HashMap<String, Object> implements OneOfRelationSource, OneOfRelationTarget {
  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    KNOWN("known"),
    UNKNOWN("unknown"),
    ANONYMOUS("anonymous"),
    USER("user");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return TypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("userKey")
  private String userKey = null;

  @SerializedName("accountId")
  private String accountId = null;

  /**
   * The account type of the user, may return empty string if unavailable. App is if the user is a bot user created on behalf of an Atlassian app.
   */
  @JsonAdapter(AccountTypeEnum.Adapter.class)
  public enum AccountTypeEnum {
    ATLASSIAN("atlassian"),
    APP("app"),
    EMPTY("");

    private String value;

    AccountTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static AccountTypeEnum fromValue(String input) {
      for (AccountTypeEnum b : AccountTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<AccountTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AccountTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public AccountTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return AccountTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("accountType")
  private AccountTypeEnum accountType = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("publicName")
  private String publicName = null;

  @SerializedName("profilePicture")
  private Icon profilePicture = null;

  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("timeZone")
  private String timeZone = null;

  @SerializedName("isExternalCollaborator")
  private Boolean isExternalCollaborator = null;

  @SerializedName("externalCollaborator")
  private Boolean externalCollaborator = null;

  @SerializedName("operations")
  private List<OperationCheckResult> operations = null;

  @SerializedName("details")
  private UserDetails details = null;

  @SerializedName("personalSpace")
  private Space personalSpace = null;

  @SerializedName("_expandable")
  private BulkUserLookupExpandable _expandable = null;

  @SerializedName("_links")
  private GenericLinks _links = null;

  public User type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public User username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @Schema(description = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public User userKey(String userKey) {
    this.userKey = userKey;
    return this;
  }

   /**
   * Get userKey
   * @return userKey
  **/
  @Schema(description = "")
  public String getUserKey() {
    return userKey;
  }

  public void setUserKey(String userKey) {
    this.userKey = userKey;
  }

  public User accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @Schema(description = "")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public User accountType(AccountTypeEnum accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * The account type of the user, may return empty string if unavailable. App is if the user is a bot user created on behalf of an Atlassian app.
   * @return accountType
  **/
  @Schema(description = "The account type of the user, may return empty string if unavailable. App is if the user is a bot user created on behalf of an Atlassian app.")
  public AccountTypeEnum getAccountType() {
    return accountType;
  }

  public void setAccountType(AccountTypeEnum accountType) {
    this.accountType = accountType;
  }

  public User email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The email address of the user. Depending on the user&#x27;s privacy setting, this may return an empty string.
   * @return email
  **/
  @Schema(description = "The email address of the user. Depending on the user's privacy setting, this may return an empty string.")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public User publicName(String publicName) {
    this.publicName = publicName;
    return this;
  }

   /**
   * The public name or nickname of the user. Will always contain a value.
   * @return publicName
  **/
  @Schema(description = "The public name or nickname of the user. Will always contain a value.")
  public String getPublicName() {
    return publicName;
  }

  public void setPublicName(String publicName) {
    this.publicName = publicName;
  }

  public User profilePicture(Icon profilePicture) {
    this.profilePicture = profilePicture;
    return this;
  }

   /**
   * Get profilePicture
   * @return profilePicture
  **/
  @Schema(description = "")
  public Icon getProfilePicture() {
    return profilePicture;
  }

  public void setProfilePicture(Icon profilePicture) {
    this.profilePicture = profilePicture;
  }

  public User displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The displays name of the user. Depending on the user&#x27;s privacy setting, this may be the same as publicName.
   * @return displayName
  **/
  @Schema(description = "The displays name of the user. Depending on the user's privacy setting, this may be the same as publicName.")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public User timeZone(String timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * This displays user time zone. Depending on the user&#x27;s privacy setting, this may return null.
   * @return timeZone
  **/
  @Schema(description = "This displays user time zone. Depending on the user's privacy setting, this may return null.")
  public String getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(String timeZone) {
    this.timeZone = timeZone;
  }

  public User isExternalCollaborator(Boolean isExternalCollaborator) {
    this.isExternalCollaborator = isExternalCollaborator;
    return this;
  }

   /**
   * Whether the user is an external collaborator user
   * @return isExternalCollaborator
  **/
  @Schema(description = "Whether the user is an external collaborator user")
  public Boolean isIsExternalCollaborator() {
    return isExternalCollaborator;
  }

  public void setIsExternalCollaborator(Boolean isExternalCollaborator) {
    this.isExternalCollaborator = isExternalCollaborator;
  }

  public User externalCollaborator(Boolean externalCollaborator) {
    this.externalCollaborator = externalCollaborator;
    return this;
  }

   /**
   * Whether the user is an external collaborator user
   * @return externalCollaborator
  **/
  @Schema(description = "Whether the user is an external collaborator user")
  public Boolean isExternalCollaborator() {
    return externalCollaborator;
  }

  public void setExternalCollaborator(Boolean externalCollaborator) {
    this.externalCollaborator = externalCollaborator;
  }

  public User operations(List<OperationCheckResult> operations) {
    this.operations = operations;
    return this;
  }

  public User addOperationsItem(OperationCheckResult operationsItem) {
    if (this.operations == null) {
      this.operations = new ArrayList<OperationCheckResult>();
    }
    this.operations.add(operationsItem);
    return this;
  }

   /**
   * Get operations
   * @return operations
  **/
  @Schema(description = "")
  public List<OperationCheckResult> getOperations() {
    return operations;
  }

  public void setOperations(List<OperationCheckResult> operations) {
    this.operations = operations;
  }

  public User details(UserDetails details) {
    this.details = details;
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @Schema(description = "")
  public UserDetails getDetails() {
    return details;
  }

  public void setDetails(UserDetails details) {
    this.details = details;
  }

  public User personalSpace(Space personalSpace) {
    this.personalSpace = personalSpace;
    return this;
  }

   /**
   * Get personalSpace
   * @return personalSpace
  **/
  @Schema(description = "")
  public Space getPersonalSpace() {
    return personalSpace;
  }

  public void setPersonalSpace(Space personalSpace) {
    this.personalSpace = personalSpace;
  }

  public User _expandable(BulkUserLookupExpandable _expandable) {
    this._expandable = _expandable;
    return this;
  }

   /**
   * Get _expandable
   * @return _expandable
  **/
  @Schema(description = "")
  public BulkUserLookupExpandable getExpandable() {
    return _expandable;
  }

  public void setExpandable(BulkUserLookupExpandable _expandable) {
    this._expandable = _expandable;
  }

  public User _links(GenericLinks _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(description = "")
  public GenericLinks getLinks() {
    return _links;
  }

  public void setLinks(GenericLinks _links) {
    this._links = _links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.type, user.type) &&
        Objects.equals(this.username, user.username) &&
        Objects.equals(this.userKey, user.userKey) &&
        Objects.equals(this.accountId, user.accountId) &&
        Objects.equals(this.accountType, user.accountType) &&
        Objects.equals(this.email, user.email) &&
        Objects.equals(this.publicName, user.publicName) &&
        Objects.equals(this.profilePicture, user.profilePicture) &&
        Objects.equals(this.displayName, user.displayName) &&
        Objects.equals(this.timeZone, user.timeZone) &&
        Objects.equals(this.isExternalCollaborator, user.isExternalCollaborator) &&
        Objects.equals(this.externalCollaborator, user.externalCollaborator) &&
        Objects.equals(this.operations, user.operations) &&
        Objects.equals(this.details, user.details) &&
        Objects.equals(this.personalSpace, user.personalSpace) &&
        Objects.equals(this._expandable, user._expandable) &&
        Objects.equals(this._links, user._links) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, username, userKey, accountId, accountType, email, publicName, profilePicture, displayName, timeZone, isExternalCollaborator, externalCollaborator, operations, details, personalSpace, _expandable, _links, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    userKey: ").append(toIndentedString(userKey)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    publicName: ").append(toIndentedString(publicName)).append("\n");
    sb.append("    profilePicture: ").append(toIndentedString(profilePicture)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    isExternalCollaborator: ").append(toIndentedString(isExternalCollaborator)).append("\n");
    sb.append("    externalCollaborator: ").append(toIndentedString(externalCollaborator)).append("\n");
    sb.append("    operations: ").append(toIndentedString(operations)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    personalSpace: ").append(toIndentedString(personalSpace)).append("\n");
    sb.append("    _expandable: ").append(toIndentedString(_expandable)).append("\n");
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
