/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.GenericLinks;
import io.swagger.client.model.User;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * UsersUserKeys
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-29T20:08:21.572793104Z[GMT]")
public class UsersUserKeys extends HashMap<String, Object> {
  @SerializedName("users")
  private List<User> users = null;

  @SerializedName("userKeys")
  private List<String> userKeys = null;

  @SerializedName("_links")
  private GenericLinks _links = null;

  public UsersUserKeys users(List<User> users) {
    this.users = users;
    return this;
  }

  public UsersUserKeys addUsersItem(User usersItem) {
    if (this.users == null) {
      this.users = new ArrayList<User>();
    }
    this.users.add(usersItem);
    return this;
  }

   /**
   * Get users
   * @return users
  **/
  @Schema(description = "")
  public List<User> getUsers() {
    return users;
  }

  public void setUsers(List<User> users) {
    this.users = users;
  }

  public UsersUserKeys userKeys(List<String> userKeys) {
    this.userKeys = userKeys;
    return this;
  }

  public UsersUserKeys addUserKeysItem(String userKeysItem) {
    if (this.userKeys == null) {
      this.userKeys = new ArrayList<String>();
    }
    this.userKeys.add(userKeysItem);
    return this;
  }

   /**
   * Get userKeys
   * @return userKeys
  **/
  @Schema(description = "")
  public List<String> getUserKeys() {
    return userKeys;
  }

  public void setUserKeys(List<String> userKeys) {
    this.userKeys = userKeys;
  }

  public UsersUserKeys _links(GenericLinks _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(description = "")
  public GenericLinks getLinks() {
    return _links;
  }

  public void setLinks(GenericLinks _links) {
    this._links = _links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersUserKeys usersUserKeys = (UsersUserKeys) o;
    return Objects.equals(this.users, usersUserKeys.users) &&
        Objects.equals(this.userKeys, usersUserKeys.userKeys) &&
        Objects.equals(this._links, usersUserKeys._links) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(users, userKeys, _links, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersUserKeys {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("    userKeys: ").append(toIndentedString(userKeys)).append("\n");
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
